### ISSUE TITLE
Letter repetition check is case-sensitive [BUG]

### ISSUE THREAD

**Issue by kryacer** [havardt/EzPasswordValidator#20]
**Describe the bug**
The passwords Aaaa@2022 or aaaA@2012 are passed.
**To Reproduce**
1. Use parameter password
2. Set LetterRepetitionLength to 4
3. Call method Validate
etc.

**Expected behavior**
Validate method returns False.

**Comment by havardt** [comment]
Thanks for bringing this to my attention.

The issue has now been fixed and a new NuGet package has been published (v2.1.0).
